name: firstworkflow
on: workflow_dispatch
jobs:
      firstjob:
        runs-on: ubuntu_latest
        steps:
          - name: greeting
            run: echo "hello world"
          - name: goodbye
            run: echo "bye"
