name: firstworkflow
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: echo "hello world"
      - name: goodbye
        run: echo "bye"
      - name: multi-line
        run: |
          echo "hello"
          echo "from the other side"
